### ISSUE TITLE
[Regression] broken highlighting with latest "patterns.begin"

### ISSUE THREAD

**Issue by mattrossman** [boyswan/vscode-glsl-literal#11]
The change introduced in #6 breaks GLSL highlighting for me with the original `glsl` template literal prefix, and I can't get the new `/* glsl */` prefix to work either. @marcofugaro are both of these working on your end?

I copied the latest code from GitHub into my `.vscode/extensions` to test this. If I delete the change from that PR in `syntaxes/glsl-literal.json`, then highlighting with a `glsl` prefix works again.

I'd really like to use the `/* glsl */` prefix, but it's not obvious why it isn't working. Wondering if I should be seeing logs somewhere that would hint at the issue.

**Comment by marcofugaro** [comment]
@mattrossman yes, it is working for me both with `/* glsl */` and `glsl` 🙂 

I've been using the latest version without any issue since last summer. The regex is solid and tested.

I think some other plugins might be interfering with this plugin in your setup.

**Comment by mattrossman** [comment]
I disabled all other plugins and reloaded, but the issue persists. This happens on both my MacBook and Windows desktop (WSL v1).

**Comment by marcofugaro** [comment]
Unfortunately I can't reproduce the issue. I have updated VSCode to latest version and everything works fine. I am on MacOS.

<img width="250" alt="Screenshot 2021-05-10 at 20 23 01" src="https://user-images.githubusercontent.com/7217420/117706489-a6d01980-b1cd-11eb-8a87-1dcc7c096998.png">
<img width="350" alt="Screenshot 2021-05-10 at 20 23 29" src="https://user-images.githubusercontent.com/7217420/117706526-b51e3580-b1cd-11eb-93ac-b6b849a07bf6.png">


@mattrossman could you try to debug this issue? Maybe it's the theme you're using, could you try switching theme?

**Comment by mattrossman** [comment]
Alas I don't use any theme, just the default. I'll try recruiting others to test if it works for them to see if there's any patterns.

**Comment by sotrh** [comment]
I'm having the same issue. I'm using v1.0.4 from the extensions library. `glsl` works but `/* glsl */` doesn't.

EDIT: I'm using Typescript

**Comment by mattrossman** [comment]
@sotrh that version is outdated (published 2 years ago) and doesn't include support for the `/* glsl */` prefix, could you try installing the latest code from the master branch on GitHub? You can download the repo as a zip file and unzip it into `~/.vscode/extensions`, then you should see the version as v1.0.5 in VS Code.

Curious to hear if either prefix works for you after that!

**Comment by sotrh** [comment]
I'm using v1.0.5, and now neither method is working.

**Comment by sotrh** [comment]
Here's the code in question.

**Comment by sotrh** [comment]
```typescript
const vertexShader = /* glsl */ `
#define STANDARD_TRIPLANAR
#include <common>
#include <morphtarget_pars_vertex>
#include <skinning_pars_vertex>
#include <lights_pars_begin>
#include <shadowmap_pars_vertex>

varying vec4 worldPosition;
varying vec3 worldNormal;
varying vec3 worldEye;

#if NUM_DIR_LIGHTS > 0
	varying vec3 vWorldDirectionalLightDirections[NUM_DIR_LIGHTS];
#endif 

void main() {
	// Creates vec3 transformed
	#include <begin_vertex>
	#include <morphtarget_vertex>
	#include <skinning_vertex>

	#include <beginnormal_vertex>
	#include <morphnormal_vertex>
	#include <skinbase_vertex>
	#include <skinnormal_vertex>
	#include <defaultnormal_vertex>

	mat3 worldNormalMatrix = mat3(transpose(inverse(modelMatrix)));
	worldPosition = modelMatrix * vec4(transformed, 1.0);
	worldNormal = worldNormalMatrix * normal;

	#include <shadowmap_vertex>

	mat4 invViewMatrix = inverse(viewMatrix);
	worldEye = vec3(invViewMatrix[3][0], invViewMatrix[3][1], invViewMatrix[3][2]);

	#if NUM_DIR_LIGHTS > 0
		mat3 invView3x3 = mat3(invViewMatrix);
		for (int i = 0; i < NUM_DIR_LIGHTS; i++) {
			vWorldDirectionalLightDirections[i] = invView3x3 * directionalLights[i].direction;
		}
	#endif

	gl_Position = projectionMatrix * modelViewMatrix * vec4(transformed, 1.0);
}
`
```

**Comment by aoitaku** [comment]
https://github.com/boyswan/vscode-glsl-literal/blob/20832cfb8d33b8b2d5b73f54e524f5a10d565804/syntaxes/glsl-literal.json#L6

```
\/\* ?glsl ?\*\/
```

This is not valid. Backslashes must be escaped in JSON string.

And any spaces may appear after comment, like:
```js
const fragment = /* glsl */ `// some glsl code`;
```

Fix as follows:

```
\\/\\* ?glsl ?\\*\\/\\s*
```

Then it works.

**Comment by mattrossman** [comment]
@aoitaku Confirming that this fixes it on my machine as well! Thank you so much for solving this, it was really bugging me.

Will you be making a PR for this?

**Comment by aoitaku** [comment]
@mattrossman Thank you for confirmation. I just made a PR #12 .

**Comment by mattrossman** [comment]
@aoitaku  For the time being I published a [personal copy ](https://github.com/mattrossman/vscode-glsl-literal)of your fork on the marketplace [here](https://marketplace.visualstudio.com/items?itemName=mattrossman.glsl-literal), since the one on the marketplace hasn't been updated for a couple of years.

**Comment by aoitaku** [comment]
@mattrossman I see, it's OK. Thanks.
