### ISSUE TITLE
use /*glsl*/ instead?

### ISSUE THREAD

**Issue by axaq** [boyswan/vscode-glsl-literal#5]
Firstly, great tool. Thanks for this.

When you use 
```javascript
const glsl = x => x;
...
const vert = glsl`...`;
```
it breaks down natural literal string methods like `replace()` later on.

Can I suggest using commented markers before the inline template literals. So that it looks like this:
```javascript
const vert = /*glsl*/`...`;
```
or this:
```javascript
const vert = `/*glsl*/ ...`;
```
Also you won't need to add the additional glsl function in this method.

**Comment by sjpt** [comment]
I agree with the previous comment; both the great tool part (thank you) and the issues part.

An alternative definition for glsl that does not break with ${} templates is
`var glsl = (a,...bb) => a.map((x,i) => [x, bb[i]]).flat().join('');`

Easier, you can use /*glsl*/ prefix if you change glsl-literal.json
at C:\Users\<user>\.vscode\extensions\boyswan.glsl-literal-1.0.4\syntaxes\glsl-literal.json
from
`(glsl|glslify|vert|frag)`
to
`(glsl|glslify|vert|frag|/\\*glsl\\*/)`

I can prepare that as a pull request if it helps boyswan make the change.
Meanwhile, edit the file and either disable and reenable the extension, or restart VS code.

(I had a lot of issues trying variants of that and having to disable comment detection and various other horrid things, but including the entire comment section was much simpler and without nasty side-effects that I can see)

**Comment by marcofugaro** [comment]
Yes please support `/* glsl */`, that's how glsl code is formatted in three.js also.

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib/background_vert.glsl.js

or 

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLCubeRenderTarget.js

**Comment by marcofugaro** [comment]
I did the PR.

**Comment by sjpt** [comment]
@marcofugaro thanks

**Comment by sjpt** [comment]
Excellent. It would be good to change the readme as well.

**Comment by boyswan** [comment]
I'm having an issue accessing my azure account in order to update the vscode plugin.. Apologies for the delays getting this up! Once I've managed to get in I'll update the readme

**Comment by sjpt** [comment]
Thanks; good luck getting account settled without too much hassle.

**Comment by boyswan** [comment]
I finally got access! Pushed and published all the latest changes

**Comment by axaq** [comment]
Hey @boyswan ,

Thanks for the update. I have updated the readme file accordingly and created a PR if you like: #13
